global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'my-monitor'

rule_files:
  - "/etc/prometheus/my-alert.rules"

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
      - targets:
        - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - 'localhost:9090'
  - job_name: 'node-exporter'
    static_configs:
      - targets:
        - 'node:9100'
  - job_name: 'alertmanager'
    static_configs:
      - targets:
        - 'alertmanager:9093'
  - job_name: 'grafana'
    static_configs:
      - targets:
        - 'grafana:3000'
  - job_name: 'pagerduty-api'
    static_configs:
      - targets:
        - 'pagerduty-api:8080'
